LANGUAGES=["en","fr","ar"]
CITIES=["Tunis","Ariana","Ben Arous","La Marsa","Carthage","Le Bardo","El Menzah","Centre Urbain Nord","Lac 1","Lac 2","Charguia","Manar","Ennasr","Sousse","Monastir","Sfax","Nabeul","Hammamet","Bizerte","Other"]
OPTIONS={
"occupation":["Student","Working professional","Freelancer","Other"],"move_in":["ASAP","Within 1 month","1–3 months","3–6 months","Flexible"],"room_type":["Private room","Shared room","Either"],"gender":["Man","Woman","Non-binary","Prefer not to say"],"roommate_gender":["Same gender only","Any gender","No preference"],"smoking":["I smoke","Okay with smokers","Non-smoking household only"],"pets":["I have pets","I like pets","No pets please","Allergic to pets"],"cleanliness":["Very tidy","Tidy","Relaxed","Messy is okay"],"noise":["Very quiet","Mostly quiet","Balanced","Social/noisy"],"sleep":["Early bird","Normal","Night owl","Irregular"],"guests":["Rarely","Sometimes","Often","Very often"],"social":["Private","Balanced","Social","Very social"],"work_home":["Never","Sometimes","Often","Always"],"drinking":["Never","Socially","Regularly"],"lease":["Short term","6 months","1 year","Flexible"]}
TRANSLATED={
"fr":{"occupation":["Étudiant","Salarié","Freelance","Autre"],"move_in":["Dès que possible","Dans 1 mois","1–3 mois","3–6 mois","Flexible"],"room_type":["Chambre privée","Chambre partagée","Les deux"],"gender":["Homme","Femme","Non-binaire","Préfère ne pas répondre"],"roommate_gender":["Même genre uniquement","Peu importe","Aucune préférence"],"smoking":["Je fume","Fumeurs acceptés","Logement non-fumeur uniquement"],"pets":["J'ai des animaux","J'aime les animaux","Pas d'animaux","Allergique aux animaux"],"cleanliness":["Très propre","Propre","Décontracté","Peu importe"],"noise":["Très calme","Plutôt calme","Équilibré","Social/bruyant"],"sleep":["Lève-tôt","Normal","Oiseau de nuit","Irrégulier"],"guests":["Rarement","Parfois","Souvent","Très souvent"],"social":["Réservé","Équilibré","Sociable","Très sociable"],"work_home":["Jamais","Parfois","Souvent","Toujours"],"drinking":["Jamais","Socialement","Régulièrement"],"lease":["Court terme","6 mois","1 an","Flexible"]},
"ar":{"occupation":["طالب","موظف","عمل حر","آخر"],"move_in":["في أقرب وقت","خلال شهر","1–3 أشهر","3–6 أشهر","مرن"],"room_type":["غرفة خاصة","غرفة مشتركة","كلاهما"],"gender":["رجل","امرأة","غير ثنائي","أفضل عدم الإجابة"],"roommate_gender":["نفس الجنس فقط","أي جنس","لا تفضيل"],"smoking":["أدخن","لا مانع من المدخنين","سكن لغير المدخنين فقط"],"pets":["لدي حيوانات","أحب الحيوانات","لا أريد حيوانات","لدي حساسية من الحيوانات"],"cleanliness":["نظيف جداً","نظيف","عادي","لا مشكلة"],"noise":["هادئ جداً","هادئ غالباً","متوازن","اجتماعي/صاخب"],"sleep":["يستيقظ مبكراً","عادي","ساهر ليلاً","غير منتظم"],"guests":["نادراً","أحياناً","غالباً","كثيراً جداً"],"social":["خاص","متوازن","اجتماعي","اجتماعي جداً"],"work_home":["أبداً","أحياناً","غالباً","دائماً"],"drinking":["أبداً","اجتماعياً","بانتظام"],"lease":["قصير المدة","6 أشهر","سنة","مرن"]}}
LABELS={"en":{"city":"Where do you want to live?","neighborhood":"Preferred neighborhood or area","occupation":"Occupation","gender":"Gender","roommate_gender":"Roommate gender preference","budget_min":"Minimum monthly budget (TND)","budget_max":"Maximum monthly budget (TND)","move_in":"Move-in timing","room_type":"Room type","smoking":"Smoking","pets":"Pets","cleanliness":"Cleanliness","noise":"Noise level","sleep":"Sleep schedule","guests":"Guests","social":"Social style","work_home":"Working/studying from home","drinking":"Drinking","lease":"Lease preference","hobbies":"Hobbies and interests","dealbreakers":"Deal-breakers","priorities":"Top priorities","compromise":"Things you can compromise on"},"fr":{"city":"Où souhaitez-vous habiter ?","neighborhood":"Quartier ou zone préférée","occupation":"Occupation","gender":"Genre","roommate_gender":"Préférence de genre du colocataire","budget_min":"Budget mensuel minimum (TND)","budget_max":"Budget mensuel maximum (TND)","move_in":"Date d'emménagement","room_type":"Type de chambre","smoking":"Tabac","pets":"Animaux","cleanliness":"Propreté","noise":"Niveau sonore","sleep":"Rythme de sommeil","guests":"Invités","social":"Style social","work_home":"Travail/études à domicile","drinking":"Alcool","lease":"Préférence de bail","hobbies":"Loisirs et centres d'intérêt","dealbreakers":"Points non négociables","priorities":"Priorités principales","compromise":"Points sur lesquels vous pouvez faire un compromis"},"ar":{"city":"أين تريد أن تسكن؟","neighborhood":"الحي أو المنطقة المفضلة","occupation":"المهنة أو الدراسة","gender":"الجنس","roommate_gender":"تفضيل جنس الشريك","budget_min":"الميزانية الشهرية الدنيا (دينار)","budget_max":"الميزانية الشهرية القصوى (دينار)","move_in":"موعد الانتقال","room_type":"نوع الغرفة","smoking":"التدخين","pets":"الحيوانات الأليفة","cleanliness":"النظافة","noise":"مستوى الضجيج","sleep":"نظام النوم","guests":"الضيوف","social":"الطابع الاجتماعي","work_home":"العمل أو الدراسة من المنزل","drinking":"الكحول","lease":"نوع عقد الإيجار","hobbies":"الهوايات والاهتمامات","dealbreakers":"الأمور غير القابلة للتفاوض","priorities":"أهم الأولويات","compromise":"الأمور التي يمكن التنازل عنها"}}
def schema(language="en"):
    language=language if language in LABELS else "en"; fields=[]
    for key,typ in [("city","select"),("neighborhood","text"),("occupation","select"),("gender","select"),("roommate_gender","select"),("budget_min","number"),("budget_max","number"),("move_in","select"),("room_type","select"),("smoking","select"),("pets","select"),("cleanliness","select"),("noise","select"),("sleep","select"),("guests","select"),("social","select"),("work_home","select"),("drinking","select"),("lease","select"),("hobbies","textarea"),("dealbreakers","textarea"),("priorities","textarea"),("compromise","textarea")]:
        f={"key":key,"type":typ,"label":LABELS[language][key]}
        if key=="city": f["options"]=CITIES
        elif key in OPTIONS: f["options"]=OPTIONS[key] if language=="en" else [{"value":v,"label":l} for v,l in zip(OPTIONS[key],TRANSLATED[language].get(key,OPTIONS[key]))]
        if typ=="number": f.update(min=300,max=5000)
        fields.append(f)
    return fields
